version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medicaldb
    volumes:
      - db_data:/var/lib/postgresql/data

  # Spring Boot Backend
  backend:
    build:
      context: ./medical
      dockerfile: Dockerfile
    container_name: spring_boot_backend
    ports:
      - "8080:8080"
    environment:
      # Auth
      OAUTH2_ISSUER: https://dev-25772036.okta.com/oauth2/default
      OAUTH2_CLIENT_ID: 0oalqfr4mpc1ZTzrE5d7
      OAUTH2_CLIENT_SECRET: ynn_gb8uklZT_Y6K2WqnqHYTFPX9QmHG_H-IkQXUIERUBZOnfi0-8gbMX5r8zBGc

      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medicaldb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  # React Frontend
  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
